export const icons = {
  back: require("./back.png"),
  add: require("./add.png"),
  anex: require("./anex.png"),
  bullet: require("./bullet.png"),
  abastecimento: require("./abastecimento.png"),
  agenda: require("./agenda.png"),
  close: require("./close.png"),
  chat: require("./chat.png"),
  camera: require("./camera.png"),
  document: require("./document.png"),
  down: require("./down.png"),
  Emergência: require("./emergencia.png"),
  Estoque: require("./estoque.png"),
  eye: require("./eye.png"),
  eyeoff: require("./eyeoff.png"),
  folder: require("./folder.png"),
  home: require("./home.png"),
  logout: require("./logout.png"),
  ocorrencias: require("./ocorrencias.png"),
  starthos: require("./logostarthos.png"),
  Manutenção: require("./manutencao.png"),
  menu: require("./menu.png"),
  Pista: require("./pista.png"),
  pouso: require("./pouso.png"),
  profile: require("./profile.png"),
  panda: require("./panda.png"),
  newPanda: require("./newPanda.png"),
  send: require("./send.png"),
  touchBranco: require("./touchBranco.png"),
  touchPreto: require("./touchPreto.png"),
  video: require("./video.png"),
  voasp: require("./voasp.png"),
  voaspbranco: require("./voaspbranco.png"),
}

export type IconTypes = keyof typeof icons
